// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn9QN4rPru3VtnkPA4QPzZQ74McnAcf0U',
    appId: '1:429658663918:web:8f11d0f7d6ad4c012e7cff',
    messagingSenderId: '429658663918',
    projectId: 'test-forminput-c0076',
    authDomain: 'test-forminput-c0076.firebaseapp.com',
    storageBucket: 'test-forminput-c0076.firebasestorage.app',
    measurementId: 'G-ENJZ7RZ3GN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtZXSm3Zae21md8YZABMdaODbWbs4baKo',
    appId: '1:429658663918:android:93060897225355d72e7cff',
    messagingSenderId: '429658663918',
    projectId: 'test-forminput-c0076',
    storageBucket: 'test-forminput-c0076.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUpfc28vyAqMLoNJy9Lh4zVbeZYF9dKwE',
    appId: '1:429658663918:ios:fbd5a26c7da9b3cc2e7cff',
    messagingSenderId: '429658663918',
    projectId: 'test-forminput-c0076',
    storageBucket: 'test-forminput-c0076.firebasestorage.app',
    iosBundleId: 'com.example.flutterForminput',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUpfc28vyAqMLoNJy9Lh4zVbeZYF9dKwE',
    appId: '1:429658663918:ios:fbd5a26c7da9b3cc2e7cff',
    messagingSenderId: '429658663918',
    projectId: 'test-forminput-c0076',
    storageBucket: 'test-forminput-c0076.firebasestorage.app',
    iosBundleId: 'com.example.flutterForminput',
  );
}
